# Generated by Django 3.1.2 on 2020-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('BlogName', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('DateCreated', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('BlogTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('BlogTypeName', models.CharField(max_length=100)),
            ],
        ),
    ]
