# Generated by Django 3.1.2 on 2020-10-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
        migrations.RenameModel(
            old_name='BlogType',
            new_name='BlogTypes',
        ),
    ]
